"""
Ralph lib - Python port of bash library functions
"""
from .date_utils import (
    get_iso_timestamp,
    get_next_hour_time,
    get_basic_timestamp,
    get_epoch_seconds,
    parse_iso_to_epoch,
)

from .file_protection import (
    RALPH_REQUIRED_PATHS,
    validate_ralph_integrity,
    get_integrity_report,
)

from .log_utils import rotate_logs

from .timeout_utils import (
    detect_timeout_command,
    has_timeout_command,
    get_timeout_status_message,
    portable_timeout,
)

from .wizard_utils import (
    confirm,
    prompt_text,
    prompt_number,
    select_option,
    select_multiple,
    select_with_default,
    print_header,
    print_bullet,
    print_success,
    print_warning,
    print_error,
    print_info,
    print_detection_result,
    show_progress,
    clear_line,
    print_summary,
    normalize_path,
    ensure_dir,
    path_relative_to,
)

from .task_sources import (
    check_beads_available,
    fetch_beads_tasks,
    get_beads_count,
    check_github_available,
    fetch_github_tasks,
    get_github_issue_count,
    get_github_labels,
    extract_prd_tasks,
    normalize_tasks,
    prioritize_tasks,
    import_tasks_from_sources,
)

from .enable_core import (
    enable_ralph_in_directory,
    safe_create_file,
    safe_create_dir,
    create_ralph_structure,
    detect_project_context,
    detect_git_info,
    detect_task_sources,
    check_existing_ralph,
    is_ralph_enabled,
    generate_prompt_md,
    generate_agent_md,
    generate_fix_plan_md,
    generate_ralphrc,
    get_templates_dir,
    enable_log,
)

from .response_analyzer import (
    detect_questions,
    detect_output_format,
    parse_json_response,
    analyze_response,
    update_exit_signals,
    log_analysis_summary,
    detect_stuck_loop,
    store_session_id,
    get_last_session_id,
    should_resume_session,
    get_iso_timestamp,
    get_epoch_seconds,
)

from .circuit_breaker import (
    CircuitBreakerState,
    CB_NO_PROGRESS_THRESHOLD,
    CB_SAME_ERROR_THRESHOLD,
    CB_OUTPUT_DECLINE_THRESHOLD,
    CB_PERMISSION_DENIAL_THRESHOLD,
    CB_COOLDOWN_MINUTES,
    CB_AUTO_RESET,
    get_iso_timestamp,
    parse_iso_to_epoch,
    init_circuit_breaker,
    get_circuit_state,
    can_execute,
    record_loop_result,
    should_halt_execution,
    reset_circuit_breaker,
)

__all__ = [
    # date_utils
    "get_iso_timestamp",
    "get_next_hour_time",
    "get_basic_timestamp",
    "get_epoch_seconds",
    "parse_iso_to_epoch",
    # file_protection
    "RALPH_REQUIRED_PATHS",
    "validate_ralph_integrity",
    "get_integrity_report",
    # log_utils
    "rotate_logs",
    # timeout_utils
    "detect_timeout_command",
    "has_timeout_command",
    "get_timeout_status_message",
    "portable_timeout",
    # wizard_utils
    "confirm",
    "prompt_text",
    "prompt_number",
    "select_option",
    "select_multiple",
    "select_with_default",
    "print_header",
    "print_bullet",
    "print_success",
    "print_warning",
    "print_error",
    "print_info",
    "print_detection_result",
    "show_progress",
    "clear_line",
    "print_summary",
    "normalize_path",
    "ensure_dir",
    "path_relative_to",
    # task_sources
    "check_beads_available",
    "fetch_beads_tasks",
    "get_beads_count",
    "check_github_available",
    "fetch_github_tasks",
    "get_github_issue_count",
    "get_github_labels",
    "extract_prd_tasks",
    "normalize_tasks",
    "prioritize_tasks",
    "import_tasks_from_sources",
    # enable_core
    "enable_ralph_in_directory",
    "safe_create_file",
    "safe_create_dir",
    "create_ralph_structure",
    "detect_project_context",
    "detect_git_info",
    "detect_task_sources",
    "check_existing_ralph",
    "is_ralph_enabled",
    "generate_prompt_md",
    "generate_agent_md",
    "generate_fix_plan_md",
    "generate_ralphrc",
    "get_templates_dir",
    "enable_log",
    # response_analyzer
    "detect_questions",
    "detect_output_format",
    "parse_json_response",
    "analyze_response",
    "update_exit_signals",
    "log_analysis_summary",
    "detect_stuck_loop",
    "store_session_id",
    "get_last_session_id",
    "should_resume_session",
    # circuit_breaker
    "CircuitBreakerState",
    "CB_NO_PROGRESS_THRESHOLD",
    "CB_SAME_ERROR_THRESHOLD",
    "CB_OUTPUT_DECLINE_THRESHOLD",
    "CB_PERMISSION_DENIAL_THRESHOLD",
    "CB_COOLDOWN_MINUTES",
    "CB_AUTO_RESET",
    "get_iso_timestamp",
    "parse_iso_to_epoch",
    "init_circuit_breaker",
    "get_circuit_state",
    "can_execute",
    "record_loop_result",
    "should_halt_execution",
    "reset_circuit_breaker",
]
