#!/usr/bin/env python3
"""
Ralph Setup - Create new Ralph project with .ralph/ subfolder structure.
"""

import argparse
import os
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def log(level: str, message: str):
    """Print colored log message."""
    colors = {
        "INFO": "\033[94m",     # Blue
        "WARN": "\033[93m",     # Yellow
        "ERROR": "\033[91m",    # Red
        "SUCCESS": "\033[92m",  # Green
    }
    reset = "\033[0m"
    color = colors.get(level, "")
    timestamp = datetime.now().strftime("%H:%M:%S")
    print(f"{color}[{timestamp}] [{level}] {message}{reset}")


def find_templates_dir(arg_templates_dir: Path = None) -> Path | None:
    """Find templates directory.

    Priority:
    1. --templates-dir argument
    2. ../templates (relative to project)
    3. ~/.ralph/templates (home directory)
    """
    if arg_templates_dir:
        if arg_templates_dir.exists():
            return arg_templates_dir
        log("ERROR", f"Templates directory not found: {arg_templates_dir}")
        return None

    # Check ../templates relative to current directory
    local_templates = Path.cwd().parent / "templates"
    if local_templates.exists():
        return local_templates

    # Check ~/.ralph/templates
    home_templates = Path.home() / ".ralph" / "templates"
    if home_templates.exists():
        return home_templates

    return None


def verify_templates(templates_dir: Path) -> bool:
    """Verify required template files exist."""
    required = ["PROMPT.md", "fix_plan.md", "AGENT.md"]
    missing = []
    for fname in required:
        if not (templates_dir / fname).exists():
            missing.append(fname)

    if missing:
        log("ERROR", f"Required template files missing: {', '.join(missing)}")
        return False
    return True


def create_project_structure(project_path: Path) -> None:
    """Create Ralph project directory structure."""
    dirs = [
        project_path / "src",
        project_path / ".ralph" / "specs" / "stdlib",
        project_path / ".ralph" / "examples",
        project_path / ".ralph" / "logs",
        project_path / ".ralph" / "docs" / "generated",
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)


def copy_templates(project_path: Path, templates_dir: Path) -> None:
    """Copy template files to .ralph/ directory."""
    # Main templates
    for fname in ["PROMPT.md", "fix_plan.md", "AGENT.md"]:
        src = templates_dir / fname
        dst = project_path / ".ralph" / fname
        if src.exists():
            shutil.copy2(src, dst)
            log("INFO", f"Copied {fname} to .ralph/")

    # Copy specs directory contents
    specs_src = templates_dir / "specs"
    specs_dst = project_path / ".ralph" / "specs"
    if specs_src.exists():
        for item in specs_src.iterdir():
            if item.is_file():
                shutil.copy2(item, specs_dst / item.name)
            elif item.is_dir():
                # Copy directory contents
                target = specs_dst / item.name
                target.mkdir(exist_ok=True)
                for subitem in item.rglob("*"):
                    if subitem.is_file():
                        rel_path = subitem.relative_to(item)
                        dest_file = target / rel_path
                        dest_file.parent.mkdir(parents=True, exist_ok=True)
                        shutil.copy2(subitem, dest_file)


def copy_gitignore(project_path: Path, templates_dir: Path) -> None:
    """Copy .gitignore template if it exists and one doesn't already exist."""
    gitignore_src = templates_dir / ".gitignore"
    gitignore_dst = project_path / ".gitignore"

    if gitignore_src.exists() and not gitignore_dst.exists():
        shutil.copy2(gitignore_src, gitignore_dst)
        log("INFO", "Copied .gitignore to project root")


def create_ralphrc(project_path: Path, project_name: str, lib_dir: Path = None) -> None:
    """Generate .ralphrc configuration file."""
    ralphrc_path = project_path / ".ralphrc"

    # Try to source enable_core.sh for generate_ralphrc function
    if lib_dir and (lib_dir / "enable_core.sh").exists():
        # For now, create inline (sourcing bash from python is complex)
        # This would need to be handled by a subprocess call to bash
        pass

    # Fallback: create minimal .ralphrc inline
    # Detect Claude Code CLI command
    claude_cmd = "claude"
    if not shutil.which("claude"):
        if shutil.which("npx"):
            claude_cmd = "npx @anthropic-ai/claude-code"

    ralphrc_content = f"""# .ralphrc - Ralph project configuration
# Generated by: ralph-setup
# Documentation: https://github.com/frankbria/ralph-claude-code

# Project identification
PROJECT_NAME="{project_name}"
PROJECT_TYPE="generic"

# Claude Code CLI command
CLAUDE_CODE_CMD="{claude_cmd}"

# Loop settings
MAX_CALLS_PER_HOUR=100
CLAUDE_TIMEOUT_MINUTES=15
CLAUDE_OUTPUT_FORMAT="json"

# Tool permissions
ALLOWED_TOOLS="Write,Read,Edit,Bash(git add *),Bash(git commit *),Bash(git diff *),Bash(git log *),Bash(git status),Bash(git status *),Bash(git push *),Bash(git pull *),Bash(git fetch *),Bash(git checkout *),Bash(git branch *),Bash(git stash *),Bash(git merge *),Bash(git tag *),Bash(npm *),Bash(pytest)"

# Session management
SESSION_CONTINUITY=true
SESSION_EXPIRY_HOURS=24

# Task sources (for ralph enable --sync)
TASK_SOURCES="local"
GITHUB_TASK_LABEL="ralph-task"
BEADS_FILTER="status:open"

# Circuit breaker thresholds
CB_NO_PROGRESS_THRESHOLD=3
CB_SAME_ERROR_THRESHOLD=5
CB_OUTPUT_DECLINE_THRESHOLD=70

# Auto-update Claude CLI at startup
CLAUDE_AUTO_UPDATE=true
"""

    ralphrc_path.write_text(ralphrc_content, encoding="utf-8")
    os.chmod(ralphrc_path, 0o600)
    log("INFO", "Created .ralphrc configuration file")


def init_git(project_path: Path) -> None:
    """Initialize git repository if not already initialized."""
    if not (project_path / ".git").exists():
        subprocess.run(["git", "init"], cwd=project_path, check=False, capture_output=True)
        log("INFO", "Initialized git repository")

        # Create initial commit
        readme_path = project_path / "README.md"
        if not readme_path.exists():
            readme_path.write_text(f"# {project_path.name}\n", encoding="utf-8")

        subprocess.run(["git", "add", "."], cwd=project_path, check=False, capture_output=True)
        subprocess.run(
            ["git", "commit", "-m", "Initial Ralph project setup"],
            cwd=project_path,
            check=False,
            capture_output=True
        )
        log("INFO", "Created initial git commit")


def setup_project(project_name: str, templates_dir: Path = None) -> Path:
    """Main setup function."""
    project_path = Path.cwd() / project_name

    log("INFO", f"Setting up Ralph project: {project_name}")

    # Create project directory
    project_path.mkdir(exist_ok=True)

    # Find templates directory
    templates = find_templates_dir(templates_dir)
    if not templates:
        log("ERROR", "Templates directory not found.")
        log("ERROR", "Expected at: --templates-dir, ../templates, or ~/.ralph/templates")
        log("ERROR", "Please run install.sh first to install Ralph globally.")
        sys.exit(1)

    log("INFO", f"Using templates from: {templates}")

    # Verify templates
    if not verify_templates(templates):
        sys.exit(1)

    # Determine lib directory
    lib_dir = None
    if (Path.cwd().parent / "lib").exists():
        lib_dir = Path.cwd().parent / "lib"
    elif (Path.home() / ".ralph" / "lib").exists():
        lib_dir = Path.home() / ".ralph" / "lib"

    # Create directory structure
    create_project_structure(project_path)

    # Copy templates
    copy_templates(project_path, templates)

    # Copy .gitignore
    copy_gitignore(project_path, templates)

    # Create .ralphrc
    create_ralphrc(project_path, project_name, lib_dir)

    # Initialize git
    init_git(project_path)

    log("SUCCESS", f"Project {project_name} created!")

    return project_path


def main():
    parser = argparse.ArgumentParser(
        description="Ralph Setup - Create new Ralph project",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  ralph_setup.py my-project
  ralph_setup.py my-project --templates-dir /path/to/templates
        """
    )
    parser.add_argument(
        "project_name",
        nargs="?",
        default="my-project",
        help="Name for the new Ralph project (default: my-project)"
    )
    parser.add_argument(
        "--templates-dir",
        type=Path,
        default=None,
        help="Path to templates directory"
    )

    args = parser.parse_args()

    try:
        project_path = setup_project(args.project_name, args.templates_dir)

        print("\nNext steps:")
        print(f"  1. Edit .ralph/PROMPT.md with your project requirements")
        print("  2. Update .ralph/specs/ with your project specifications")
        print("  3. Run: ralph --monitor")
    except Exception as e:
        log("ERROR", f"Setup failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
