#!/usr/bin/env python3
"""
Ralph Project Setup Script

Creates a new Ralph-managed project with the proper directory structure,
templates, and configuration files.
"""

import click
import os
import shutil
import subprocess
from pathlib import Path
from typing import Optional, List


# ANSI color codes for output
RED = "\033[0;31m"
GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
BLUE = "\033[0;34m"
NC = "\033[0m"


def log(level: str, message: str) -> None:
    """Print a colored log message."""
    color = {"INFO": BLUE, "WARN": YELLOW, "ERROR": RED, "SUCCESS": GREEN}.get(level, "")
    print(f"{color}[{level}] {message}{NC}")


def find_templates_dir(script_dir: Path) -> Optional[Path]:
    """
    Find the templates directory.

    Search order:
    1. Local ../templates (relative to project directory)
    2. Global ~/.ralph/templates

    Returns:
        Path to templates directory or None if not found
    """
    # Check local templates first (../templates relative to script)
    local_templates = script_dir.parent.parent / "templates"
    if local_templates.exists():
        return local_templates

    # Check global templates
    global_templates = Path.home() / ".ralph" / "templates"
    if global_templates.exists():
        return global_templates

    return None


def find_lib_dir(script_dir: Path) -> Optional[Path]:
    """
    Find the lib directory.

    Search order:
    1. Local ../lib (relative to script directory)
    2. Global ~/.ralph/lib

    Returns:
        Path to lib directory or None if not found
    """
    # Check local lib first
    local_lib = script_dir.parent.parent / "lib"
    if local_lib.exists():
        return local_lib

    # Check global lib
    global_lib = Path.home() / ".ralph" / "lib"
    if global_lib.exists():
        return global_lib

    return None


def detect_claude_command() -> str:
    """
    Detect the best available Claude Code CLI command.

    Returns:
        "claude" if available, otherwise "npx @anthropic-ai/claude-code"
    """
    if shutil.which("claude"):
        return "claude"
    elif shutil.which("npx"):
        return "npx @anthropic-ai/claude-code"
    else:
        return "npx @anthropic-ai/claude-code"


def create_ralphrc(project_name: str, project_type: str = "generic") -> str:
    """
    Generate .ralphrc configuration file content.

    Args:
        project_name: Name of the project
        project_type: Type of project (generic, javascript, python, etc.)

    Returns:
        Content for the .ralphrc file
    """
    claude_cmd = detect_claude_command()

    return f'''# .ralphrc - Ralph project configuration
# Generated by: ralph-setup
# Documentation: https://github.com/frankbria/ralph-claude-code

# Project identification
PROJECT_NAME="{project_name}"
PROJECT_TYPE="{project_type}"

# Claude Code CLI command
# If "claude" is not in your PATH, set to your installation:
#   "npx @anthropic-ai/claude-code"  (uses npx, no global install needed)
#   "/path/to/claude"                (custom path)
CLAUDE_CODE_CMD="{claude_cmd}"

# Loop settings
MAX_CALLS_PER_HOUR=100
CLAUDE_TIMEOUT_MINUTES=15
CLAUDE_OUTPUT_FORMAT="json"

# Tool permissions
# Comma-separated list of allowed tools
# Safe git subcommands only - broad Bash(git *) allows destructive commands like git clean/git rm
ALLOWED_TOOLS="Write,Read,Edit,Bash(git add *),Bash(git commit *),Bash(git diff *),Bash(git log *),Bash(git status),Bash(git status *),Bash(git push *),Bash(git pull *),Bash(git fetch *),Bash(git checkout *),Bash(git branch *),Bash(git stash *),Bash(git merge *),Bash(git tag *),Bash(npm *),Bash(pytest)"

# Session management
SESSION_CONTINUITY=true
SESSION_EXPIRY_HOURS=24

# Task sources (for ralph enable --sync)
# Options: local, beads, github (comma-separated for multiple)
TASK_SOURCES="local"
GITHUB_TASK_LABEL="ralph-task"
BEADS_FILTER="status:open"

# Circuit breaker thresholds
CB_NO_PROGRESS_THRESHOLD=3
CB_SAME_ERROR_THRESHOLD=5
CB_OUTPUT_DECLINE_THRESHOLD=70

# Auto-update Claude CLI at startup
CLAUDE_AUTO_UPDATE=true
'''


def copy_template_files(templates_dir: Path, project_dir: Path) -> List[str]:
    """
    Copy template files to the project directory.

    Args:
        templates_dir: Source templates directory
        project_dir: Target project directory

    Returns:
        List of copied file paths
    """
    copied = []
    ralph_dir = project_dir / ".ralph"

    # Template files to copy to .ralph/
    ralph_templates = ["PROMPT.md", "fix_plan.md", "AGENT.md"]
    for template in ralph_templates:
        src = templates_dir / template
        if src.exists():
            dst = ralph_dir / template
            shutil.copy2(src, dst)
            copied.append(str(dst))

    # Copy specs directory contents
    specs_src = templates_dir / "specs"
    specs_dst = ralph_dir / "specs"
    if specs_src.exists():
        specs_dst.mkdir(parents=True, exist_ok=True)
        for item in specs_src.iterdir():
            if item.is_file():
                shutil.copy2(item, specs_dst)
                copied.append(str(specs_dst / item.name))

    # Copy .gitignore if exists and no .gitignore in project
    gitignore_src = templates_dir / ".gitignore"
    gitignore_dst = project_dir / ".gitignore"
    if gitignore_src.exists() and not gitignore_dst.exists():
        shutil.copy2(gitignore_src, gitignore_dst)
        copied.append(str(gitignore_dst))

    return copied


def init_git_repo(project_dir: Path) -> bool:
    """
    Initialize a git repository if one doesn't exist.

    Args:
        project_dir: Project directory

    Returns:
        True if git was initialized, False if already exists or failed
    """
    git_dir = project_dir / ".git"
    if git_dir.exists():
        return False

    try:
        subprocess.run(
            ["git", "init"],
            cwd=project_dir,
            check=True,
            capture_output=True,
            text=True,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def create_initial_commit(project_dir: Path, project_name: str) -> bool:
    """
    Create the initial git commit.

    Args:
        project_dir: Project directory
        project_name: Name of the project

    Returns:
        True if commit succeeded, False otherwise
    """
    try:
        # Create initial README.md
        readme_path = project_dir / "README.md"
        readme_path.write_text(f"# {project_name}\n")

        subprocess.run(
            ["git", "add", "."],
            cwd=project_dir,
            check=True,
            capture_output=True,
            text=True,
        )
        subprocess.run(
            ["git", "commit", "-m", "Initial Ralph project setup"],
            cwd=project_dir,
            check=True,
            capture_output=True,
            text=True,
        )
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


@click.command()
@click.argument("project_name", default="my-project")
@click.option(
    "--templates-dir",
    type=click.Path(exists=True, file_okay=False, dir_okay=True, path_type=Path),
    default=None,
    help="Override templates directory location",
)
def setup(project_name: str, templates_dir: Optional[Path]) -> None:
    """
    Create a new Ralph project.

    PROJECT_NAME: Name of the project to create (default: my-project)

    This command creates a new project directory with:
    - .ralph/ subfolder containing configuration and templates
    - src/ directory for source code
    - .ralphrc configuration file
    - Git repository with initial commit
    """
    # Determine script directory
    script_dir = Path(__file__).parent.resolve()

    # Find templates directory
    if templates_dir is None:
        templates_dir = find_templates_dir(script_dir)

    if templates_dir is None:
        log("ERROR", "Templates directory not found.")
        print("  Expected at: ../templates or ~/.ralph/templates")
        print("  Please run 'ralph-install' first to install Ralph globally.")
        raise click.Abort()

    # Verify required template files
    if not (templates_dir / "PROMPT.md").exists():
        log("ERROR", f"Required template file PROMPT.md not found in {templates_dir}")
        raise click.Abort()

    log("INFO", f"Setting up Ralph project: {project_name}")

    # Create project directory
    project_dir = Path(project_name)
    project_dir.mkdir(parents=True, exist_ok=True)

    # Create directory structure
    (project_dir / "src").mkdir(exist_ok=True)
    (project_dir / ".ralph" / "specs" / "stdlib").mkdir(parents=True, exist_ok=True)
    (project_dir / ".ralph" / "examples").mkdir(exist_ok=True)
    (project_dir / ".ralph" / "logs").mkdir(exist_ok=True)
    (project_dir / ".ralph" / "docs" / "generated").mkdir(parents=True, exist_ok=True)

    # Copy template files
    copied_files = copy_template_files(templates_dir, project_dir)
    for f in copied_files:
        log("SUCCESS", f"Created: {f}")

    # Generate .ralphrc configuration
    ralphrc_path = project_dir / ".ralphrc"
    ralphrc_content = create_ralphrc(project_name)
    ralphrc_path.write_text(ralphrc_content)
    os.chmod(ralphrc_path, 0o600)
    log("SUCCESS", f"Created: {ralphrc_path}")

    # Initialize git repository
    if init_git_repo(project_dir):
        log("SUCCESS", "Initialized git repository")
        if create_initial_commit(project_dir, project_name):
            log("SUCCESS", "Created initial commit")

    log("SUCCESS", f"Project {project_name} created!")
    print("\nNext steps:")
    print("  1. Edit .ralph/PROMPT.md with your project requirements")
    print("  2. Update .ralph/specs/ with your project specifications")
    print("  3. Run: ralph --monitor")
    print("  4. Monitor: ralph-monitor")


if __name__ == "__main__":
    setup()
